// ─────────────────────────────────────────────────────────────
// HEBREW FLASHCARD DICTIONARY
// ─────────────────────────────────────────────────────────────
// Each entry's key (e.g. "1") is the card ID. It must match the
// audio filename you record: 1.mp3 (or 1.m4a / 1.ogg) goes in
// the audio/ folder next to index.html.
//
// "word"  → the Hebrew text shown on the card
// "emoji" → one emoji shown above the word
// ─────────────────────────────────────────────────────────────

const CARDS = {
  "1":   { word: "ירקות",         emoji: "🥬" },
  "2":   { word: "פירות",         emoji: "🍎" },
  "3":   { word: "מאפייה",        emoji: "🍞" },
  "4":   { word: "גזר",           emoji: "🥕" },
  "5":   { word: "תפוח",          emoji: "🍎" },
  "6":   { word: "לחם",           emoji: "🍞" },
  "7":   { word: "עגבנייה",        emoji: "🍅" },
  "8":   { word: "בננה",          emoji: "🍌" },
  "9":   { word: "בייגל",         emoji: "🥯" },
  "10":  { word: "מלפפון",        emoji: "🥒" },
  "11":  { word: "תפוז",          emoji: "🍊" },
  "12":  { word: "פיתה",          emoji: "🫓" },
  "13":  { word: "בצל",           emoji: "🧅" },
  "14":  { word: "ענבים",         emoji: "🍇" },
  "15":  { word: "בגט",           emoji: "🥖" },
  "16":  { word: "תפוח אדמה",      emoji: "🥔" },
  "17":  { word: "תות",           emoji: "🍓" },
  "18":  { word: "קרואסון",       emoji: "🥐" },
  "19":  { word: "חסה",           emoji: "🥬" },
  "20":  { word: "אבטיח",         emoji: "🍉" },
  "21":  { word: "חלה",           emoji: "🥖" },
  "22":  { word: "פלפל",          emoji: "🫑" },
  "23":  { word: "אבוקדו",        emoji: "🥑" },
  "24":  { word: "מאפין",         emoji: "🧁" },
  "25":  { word: "ברוקולי",       emoji: "🥦" },
  "26":  { word: "אננס",          emoji: "🍍" },
  "27":  { word: "עוגיות",        emoji: "🍪" },

  "28":  { word: "בשר ודגים",      emoji: "🥩" },
  "29":  { word: "מוצרי חלב",      emoji: "🥛" },
  "30":  { word: "ביצים",         emoji: "🥚" },
  "31":  { word: "בקר",           emoji: "🥩" },
  "32":  { word: "חלב",           emoji: "🥛" },
  "33":  { word: "ביצים",         emoji: "🥚" },
  "34":  { word: "עוף",           emoji: "🍗" },
  "35":  { word: "גבינה",         emoji: "🧀" },
  "36":  { word: "בייקון",        emoji: "🥓" },
  "37":  { word: "חמאה",          emoji: "🧈" },
  "38":  { word: "נקניקיות",       emoji: "🌭" },
  "39":  { word: "יוגורט",        emoji: "🥣" },
  "40":  { word: "הודו",          emoji: "🦃" },
  "41":  { word: "שמנת",          emoji: "🥛" },
  "42":  { word: "דג",            emoji: "🐟" },
  "43":  { word: "קוטג׳",         emoji: "🧀" },

  "44":  { word: "מזווה",         emoji: "🍚" },
  "45":  { word: "שימורים",       emoji: "🥫" },
  "46":  { word: "תבלינים",       emoji: "🧂" },
  "47":  { word: "אורז",          emoji: "🍚" },
  "48":  { word: "שעועית",        emoji: "🫘" },
  "49":  { word: "מלח",           emoji: "🧂" },
  "50":  { word: "פסטה",          emoji: "🍝" },
  "51":  { word: "תירס",          emoji: "🌽" },
  "52":  { word: "פלפל",          emoji: "⚫" },
  "53":  { word: "קמח",           emoji: "🌾" },
  "54":  { word: "טונה",          emoji: "🥫" },
  "55":  { word: "אבקת שום",       emoji: "🧄" },
  "56":  { word: "שיבולת שועל",    emoji: "🥣" },
  "57":  { word: "רסק עגבניות",    emoji: "🍅" },
  "58":  { word: "אבקת בצל",       emoji: "🧅" },
  "59":  { word: "עדשים",         emoji: "🫘" },
  "60":  { word: "אפונה",         emoji: "🫛" },
  "61":  { word: "אורגנו",        emoji: "🌿" },
  "62":  { word: "סוכר",          emoji: "🧂" },
  "63":  { word: "בזיליקום",      emoji: "🌿" },
  "64":  { word: "דבש",           emoji: "🍯" },
  "65":  { word: "פפריקה",        emoji: "🌶️" },

  "66":  { word: "משקאות",        emoji: "🥤" },
  "67":  { word: "חטיפים",        emoji: "🍿" },
  "68":  { word: "ניקיון",        emoji: "🧼" },
  "69":  { word: "מים",           emoji: "💧" },
  "70":  { word: "צ׳יפס",         emoji: "🍟" },
  "71":  { word: "נייר טואלט",     emoji: "🧻" },
  "72":  { word: "קולה",          emoji: "🥤" },
  "73":  { word: "פופקורן",       emoji: "🍿" },
  "74":  { word: "מגבות נייר",     emoji: "🧻" },
  "75":  { word: "מיץ",           emoji: "🧃" },
  "76":  { word: "שוקולד",        emoji: "🍫" },
  "77":  { word: "סבון",          emoji: "🧼" },
  "78":  { word: "קפה",           emoji: "☕" },
  "79":  { word: "עוגיות",        emoji: "🍪" },
  "80":  { word: "שמפו",          emoji: "🧴" },
  "81":  { word: "תה",            emoji: "🍵" },
  "82":  { word: "אגוזים",        emoji: "🥜" },
  "83":  { word: "ספוג",          emoji: "🧽" },
  "84":  { word: "חלב שקדים",      emoji: "🥛" },
  "85":  { word: "סוכריות",       emoji: "🍬" },
  "86":  { word: "אבקת כביסה",     emoji: "🧺" },

  "87":  { word: "קפואים",        emoji: "❄️" },
  "88":  { word: "שונות",         emoji: "🌮" },
  "89":  { word: "קרח",           emoji: "🧊" },
  "90":  { word: "טורטיות",       emoji: "🌮" },
  "91":  { word: "פיצה",          emoji: "🍕" },
  "92":  { word: "חומוס",         emoji: "🌯" },
  "93":  { word: "צ׳יפס קפוא",     emoji: "🍟" },
  "94":  { word: "זיתים",         emoji: "🫒" },
  "95":  { word: "כיסונים",       emoji: "🥟" },
  "96":  { word: "חמוצים",        emoji: "🥒" },
  "97":  { word: "פלאפל",         emoji: "🧆" },
  "98":  { word: "טחינה",         emoji: "🥜" },
  "99":  { word: "גלידה",         emoji: "🍦" },
  "100": { word: "שמן זית",        emoji: "🫒" },
};
